# -*- coding: utf-8 -*-
"""2_decision_tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKSZ0uXgF5T9HkFLCipPRcAZbrqTcyzm
"""

# Decision Tree on Titanic dataset (using limited features)

import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load Titanic dataset
df = sns.load_dataset('titanic')

# Using a few basic features and dropping nulls
df = df[['survived', 'pclass', 'age', 'fare']].dropna()
X = df[['pclass', 'age', 'fare']]
y = df['survived']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

# Train the model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Decision Tree Accuracy:", accuracy)