# -*- coding: utf-8 -*-
"""3_knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rzrm97-Ha5PYMOwkO9ueMhSWP8K4w_3w
"""

# KNN on Digits dataset

from sklearn.datasets import load_digits
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Load digits dataset
digits = load_digits()
X = digits.data
y = digits.target

# Scale the data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

# KNN model (default: k=5)
model = KNeighborsClassifier()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("KNN Accuracy:", accuracy)