# -*- coding: utf-8 -*-
"""4_svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T5JBgDPCZzI5sCk5InmIfjMvByD58aGj
"""

# SVM on Breast Cancer dataset

from sklearn.datasets import load_breast_cancer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Load data
cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

# SVM model (using default RBF kernel)
model = SVC()
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("SVM Accuracy:", accuracy)